---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install tools
  apt:
    name: [ 'iputils-arping' ]
    state: present
    update_cache: yes

- name: install confd files
  include_tasks: ../../utils/tasks/process-confd-files.yml
